### ISSUE TITLE
ERROR from UglifyJs

### ISSUE THREAD

**Issue by cyseria** [be-fe/issue-reporter-web#2]
when I use UglifyJsPlugin in `webpack`(babel exclude: /node_modules/)
it will occur some error 😵

```
ERROR in js/login.js from UglifyJs
 [./node_modules/copy-text-to-clipboard/index.js:2,0][js/login.js:28283,24]
```

coz  `uglifyjs-webpack-plugin` 2.x depend on uglify-js, while uglify-js only supports JavaScript (ECMAScript 5) 

could you consider using other package or write yourself instead of using `copy-text-to-clipboard`?

Thanks

**Comment by cyseria** [comment]
if necessary, recommend [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin)  to compile es6 🙃

**Comment by imcuttle** [comment]
@cyseria, Thanks for your good first issue. I had the plan to optimize the logic of copying text for the below reasons:

1. Some legacy browsers fail to copy text.
2. The words that you said (be compatible with es5)

**Comment by imcuttle** [comment]
Hi, @cyseria , I had supported [`shouldopenurlinsamewindow`](https://github.com/be-fe/issue-reporter-web#shouldopenurlinsamewindow) in `0.1.0`. 

PS, It's low priority about using es5 library which copies text in browser like [copy-text-to-clipboard](https://github.com/sindresorhus/copy-text-to-clipboard#readme) for me. 
And welcome your PR!
